### PR TITLE
ci: :construction_worker: improve GitHub Actions workflows

### PR DESCRIPTION
**Pull request by ap0nia**
# Summary

## Features
- All workflow files have a `yaml-language-server` schema comment at the top of the file to specify the schema for the [YAML LSP](https://github.com/redhat-developer/yaml-language-server), which is helpful for developers that use code editors that rely on LSPs for code analysis (i.e. VSCode, NeoVim, not JetBrains)
- All jobs and steps have a name, which can provide more insight into what it does (or sometimes the job name is the same as the workflow name because there's nothing else to describe lol, but it's there anyways for consistency)
- all related deployment processes are consolidated into a single workflow
  - `deploy-staging.yml` - deploys staging environments for the API and documentation during a pull request
  - `deploy-prod.yml` - deploys production environments for the API and documentation
  - `destroy-staging.yml` - destroys the staging environments for the API and documentation after a pull request is closed

## Notes
~~The workflow files can't be renamed immediately, otherwise they won't be triggered since they don't exist on the main branch. Maybe open another PR with `no-deploy` to change the names afterward? Or push directly to main if you have admin permissions.~~ skill issue; I swear I've been harassed by this random issue before lol

### CODE REVIEW

**Comment by ecxyzzy** [comment]
> The workflow files can't be renamed immediately, otherwise they won't be triggered since they don't exist on the main branch. Maybe open another PR with no-deploy to change the names afterward? Or push directly to main if you have admin permissions.

Wait actually? I remember renaming `conventional-pr.yml` to `lint-pr.yml` for #69 and it ran fine on the PR.

**Comment by ecxyzzy** [comment]
Also is there a reason the `lint-and-format-pr` action didn't re-fire on PR name change?

**Comment by ap0nia** [comment]
I feel like that could've been the `conventional-pr.yml` running from the main branch; not the one running from the feature branch. i.e. It was running the old workflow that just did a conventional-commit check, instead of the linting + formatting/updating the PR title.

There's an open issue and the general consensus is to create a workflow file that exists on the main branch before testing it on development branches https://github.com/orgs/community/discussions/25746

I don't really get all these workflow shenanigans lol

**Comment by ecxyzzy** [comment]
Nope, it definitely ran the new workflow:
https://github.com/icssc/peterportal-api-next/actions/runs/5859266473/job/15884907857

**Comment by ap0nia** [comment]
Ok, let me try

**Comment by ap0nia** [comment]
> Also is there a reason the `lint-and-format-pr` action didn't re-fire on PR name change? I tried rerunning it manually, but it seems to be using the old PR title for some reason.

Ok, so by default "runs on pull_request" means "opened, synchronize, or reopened" ; I added "edited" too

**Review by ecxyzzy — APPROVED** [review]
This is definitely a lot cleaner than the previous implementation. Great work! :rocket:

**Pull request merged**
